from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

#Raw PostgreSQL Statement For Creating Table Aforementioned Post Model
#CREATE TABLE "posts_post" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(75) NOT NULL, "body" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "modified_at" timestamp with time zone NOT NULL);

    def __str__(self) -> str:
        return self.title
    

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"id": self.pk})
    